const HUNGERFILL_DATA = {
  company: {
    name: "Hungerfill Foods",
    legal: "Hunger Fill Foodstuff Trading LLC",
    tagline: "Premium Frozen & Fresh Food Trading from Dubai, UAE",
    address: "Dubai, U.A.E",
    phone: "050 5056049",
    email: "info@hungerfill.com",
    sales: "sales@hungerfill.com",
    linkedin: "https://www.linkedin.com/company/hungerfill-foods/",
    instagram: "https://www.instagram.com/hungerfillfoods",
    domain: "https://hungerfill.com"
  },

  productDropdown: [
    { id: "seafood", label: "Seafood", icon: "🦐", path: "products/seafood.html" },
    { id: "meat", label: "Meat", icon: "🥩", path: "products/meat.html" },
    { id: "poultry", label: "Poultry", icon: "🍗", path: "products/poultry.html" },
    { id: "eggs", label: "Eggs", icon: "🥚", path: "products/eggs.html" },
    { id: "other", label: "Others", icon: "🌾", path: "products/other.html" }
  ],

  categories: [
    {
      id: "seafood",
      name: "Frozen Seafood",
      icon: "🦐",
      description: "Premium frozen seafood sourced from certified fisheries worldwide.",
      path: "products/seafood.html",
      writeup: `<p>Dubai sits at the crossroads of global seafood trade, and frozen seafood is the backbone of the UAE's F&amp;B industry. From hotel banquets on the Palm to neighbourhood grills in Deira, demand spans Arabic hamour and shrimps, Asian pomfret and squid, and European salmon and scallops. Hungerfill Foods supplies a full frozen seafood portfolio — blast-frozen at source and delivered through temperature-controlled logistics across Dubai and the GCC.</p>
      <p>Our range covers shrimps, rock and sand lobster, crab, white and black pomfret, Nile perch and hamour fillets, salmon fillet, squid (whole and trimmed), seafood mix, pangasius (basa/douri) and scallops — giving buyers a single Dubai partner for diverse menu requirements.</p>
      <h3>Channels &amp; Opportunities in Dubai &amp; the GCC</h3>
      <ul>
        <li><strong>Hotels &amp; Resorts:</strong> Five-star properties across Dubai, Abu Dhabi and Ras Al Khaimah drive demand for premium fillets, lobster and scallops for buffets and fine dining.</li>
        <li><strong>Restaurants &amp; Cloud Kitchens:</strong> Seafood grills, Asian cuisine, fish &amp; chips and delivery kitchens rely on consistent IQF portions and competitive pricing.</li>
        <li><strong>Supermarkets &amp; Retail:</strong> Hypermarkets and independent seafood counters need graded whole fish and fillets with reliable weekly supply.</li>
        <li><strong>Catering &amp; Institutional:</strong> Airline catering, school meals and corporate events require bulk packs with uniform sizing.</li>
        <li><strong>Re-export:</strong> Dubai's free-zone infrastructure enables traders to supply Oman, Bahrain, Qatar and Saudi Arabia within 48 hours.</li>
      </ul>`
    },
    {
      id: "poultry",
      name: "Poultry",
      icon: "🍗",
      description: "Frozen chicken products for retail, HORECA and catering operations.",
      path: "products/poultry.html",
      writeup: `<p>Chicken is the most consumed protein in the UAE, and frozen poultry gives foodservice operators cost control, longer shelf life and consistent portion sizes. Hungerfill Foods supplies halal-certified frozen chicken — whole bird, breast fillets and leg quarters — sourced from approved processing plants and stored under strict cold-chain conditions in Dubai.</p>
      <p>Whether you run a rotisserie counter, a hotel kitchen or a catering operation feeding thousands daily, our poultry line is built for volume, reliability and competitive wholesale pricing.</p>
      <h3>Channels &amp; Opportunities in Dubai &amp; the GCC</h3>
      <ul>
        <li><strong>Hotels &amp; Catering:</strong> Breast fillets for grills and salads; leg quarters for buffets and BBQ stations; whole chicken for roastery and banquet service.</li>
        <li><strong>Restaurants &amp; QSR:</strong> Frozen breast and leg portions reduce waste and simplify prep for high-turnover kitchens.</li>
        <li><strong>Supermarkets:</strong> Whole chicken and portion packs for retail freezers with consistent grading and halal labelling.</li>
        <li><strong>Labour &amp; Institutional Catering:</strong> Bulk supply for worker accommodation camps and cafeteria operators across the UAE and GCC.</li>
        <li><strong>Export &amp; Re-export:</strong> Dubai-based consolidation for poultry shipments to neighbouring emirates and GCC markets.</li>
      </ul>`
    },
    {
      id: "meat",
      name: "Meat",
      icon: "🥩",
      description: "Fresh and frozen Indian mutton and beef cuts with full cold-chain integrity.",
      path: "products/meat.html",
      writeup: `<p>The UAE's diverse population creates strong demand for authentic Indian mutton (goat) and beef cuts alongside local and imported lamb. Hungerfill Foods specialises in fresh and frozen Indian mutton carcass and a full range of frozen Indian beef cuts — halal certified and handled with care from abattoir to delivery.</p>
      <p>From traditional biryanis and karahi to stew cuts and mince for kebabs, our meat products serve butcheries, hotels and restaurants that demand authentic flavour profiles and consistent quality.</p>
      <h3>Channels &amp; Opportunities in Dubai &amp; the GCC</h3>
      <ul>
        <li><strong>Butcheries &amp; Meat Shops:</strong> Whole and half carcass for in-store cutting; popular in areas with strong South Asian and Arab communities.</li>
        <li><strong>Hotels &amp; Restaurants:</strong> Mutton for Arabic haneeth, Yemeni mandi and South Asian curries; beef cubes and mince for grills and stews.</li>
        <li><strong>Catering &amp; Events:</strong> Bulk mutton and beef for weddings, Ramadan iftar spreads and large-scale catering in Dubai and Sharjah.</li>
        <li><strong>Retail Chains:</strong> Pre-cut frozen portions for supermarket meat sections serving expatriate communities.</li>
        <li><strong>GCC Distribution:</strong> Dubai as a hub for meat re-export to Oman, Bahrain and Saudi markets with growing demand for halal Indian-origin meat.</li>
      </ul>`
    },
    {
      id: "eggs",
      name: "Eggs",
      icon: "🥚",
      description: "High-quality eggs for commercial kitchens and foodservice buyers.",
      path: "products/eggs.html",
      writeup: `<p>Eggs are an essential staple for every commercial kitchen — from five-star hotel pastry sections to neighbourhood bakeries and cloud kitchen breakfast menus. Hungerfill Foods supplies fresh Grade A eggs in tray and bulk packs with reliable weekly delivery across Dubai and the UAE.</p>
      <p>Consistent shell quality, uniform sizing and dependable supply make our eggs the practical choice for bakeries, hotels, cafés and institutional buyers who cannot afford stockouts.</p>
      <h3>Channels &amp; Opportunities in Dubai &amp; the GCC</h3>
      <ul>
        <li><strong>Bakeries &amp; Pastry Shops:</strong> High-volume egg consumption for cakes, pastries, bread and confectionery across Dubai's thriving bakery sector.</li>
        <li><strong>Hotels &amp; Restaurants:</strong> Breakfast buffets, brunch service, desserts and sauce production require steady egg supply.</li>
        <li><strong>Cloud Kitchens &amp; Delivery:</strong> Breakfast-focused delivery brands depend on reliable egg procurement at scale.</li>
        <li><strong>Supermarkets &amp; Retail:</strong> Tray packs for consumer shelves in hypermarkets and neighbourhood grocers.</li>
        <li><strong>Food Manufacturing:</strong> Mayonnaise, pasta and ready-meal producers across the UAE and wider GCC.</li>
      </ul>`
    },
    {
      id: "other",
      name: "Other Products",
      icon: "🌾",
      description: "Dates, ghee, vegetables, grains, fruits, cheese and dairy essentials.",
      path: "products/other.html",
      writeup: `<p>Beyond proteins, commercial kitchens and retailers need a reliable basket of dry goods, dairy, produce and specialty items. Hungerfill Foods complements our core seafood, poultry and meat lines with dates, ghee, vegetables, grains &amp; cereals, fruits, cheese and dairy products — helping buyers consolidate procurement through a single Dubai-based partner.</p>
      <p>From Ramadan date promotions to daily rice supply for catering operations, these products round out the offering for hotels, supermarkets, restaurants and distributors across the region.</p>
      <h3>Channels &amp; Opportunities in Dubai &amp; the GCC</h3>
      <ul>
        <li><strong>Supermarkets &amp; Hypermarkets:</strong> Dates, ghee, rice and dairy are high-velocity SKUs especially during Ramadan and festive seasons.</li>
        <li><strong>Hotels &amp; Hospitality:</strong> Welcome trays with premium dates, ghee for traditional cooking, and imported fruits for breakfast buffets.</li>
        <li><strong>Restaurants &amp; Cafés:</strong> Cheese for pizzerias and delis; vegetables and grains for daily kitchen operations.</li>
        <li><strong>Food Manufacturing &amp; Bakeries:</strong> Ghee, dairy and grains as raw materials for sweets, bread and ready-meal production.</li>
        <li><strong>Gift &amp; Corporate:</strong> Premium date assortments for corporate gifting — a growing segment in Dubai and across the GCC.</li>
      </ul>`
    }
  ],

  products: [
    { slug: "shrimps", name: "Shrimps", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Shrimps.png", short: "Premium frozen shrimps in multiple sizes for restaurants and retailers.", description: "Our frozen shrimps are sourced from certified aquaculture and wild-catch fisheries, blast-frozen at source to lock in freshness. Available in HOSO, HLSO, PUD, PDTO and peeled varieties with consistent sizing for portion control.", features: ["Multiple sizes: U15 to 71/90", "IQF and block frozen options", "Export-quality grading", "Ideal for hotels, restaurants & retail"], keywords: "frozen shrimp Dubai, shrimp supplier UAE, HOSO shrimp Dubai, seafood trading UAE" },
    { slug: "rock-lobster", name: "Rock Lobster", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Rock_Lobster.png", short: "Wild-caught rock lobster for premium dining and hospitality.", description: "Rock lobster (spiny lobster) delivered frozen with strict temperature control. Perfect for fine dining, hotel banquets and specialty seafood counters across the GCC.", features: ["Whole and tail portions", "Consistent cold-chain handling", "Premium grade selection", "Custom pack sizes available"], keywords: "rock lobster Dubai, frozen lobster UAE, spiny lobster supplier Dubai" },
    { slug: "sand-lobster", name: "Sand Lobster", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Sand_Lobster.png", short: "Sand lobster (slipper lobster) for diverse menu applications.", description: "Sand lobster offers excellent meat yield and a distinctive flavor profile. We supply frozen whole and processed cuts suitable for Arabic, Asian and European cuisine formats.", features: ["Whole and half-cut options", "Blast-frozen at source", "Quality-controlled processing", "Reliable GCC distribution"], keywords: "sand lobster Dubai, slipper lobster UAE, frozen lobster supplier" },
    { slug: "crab", name: "Crab", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Crab.png", short: "Frozen crab — whole, sections and claw meat for foodservice.", description: "From blue swimming crab to king crab varieties, we supply frozen crab products that meet the demands of buffets, seafood restaurants and retail seafood counters.", features: ["Whole, sections & claw meat", "IQF and master carton packs", "Export-grade quality", "Year-round availability"], keywords: "frozen crab Dubai, crab supplier UAE, blue crab Dubai" },
    { slug: "white-pomfret", name: "White Pomfret", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_White_Pomfret.png", short: "White pomfret — a Gulf favorite for grills, fries and traditional dishes.", description: "White pomfret is one of the most sought-after fish in the Middle East. We supply frozen whole and cleaned fish with consistent grading for supermarkets and restaurants.", features: ["Whole & gutted options", "Multiple size grades", "Popular in Arabic & Asian cuisine", "GCC-wide delivery"], keywords: "white pomfret Dubai, frozen pomfret UAE, fish supplier Dubai" },
    { slug: "black-pomfret", name: "Black Pomfret", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Black_Pomfret.png", short: "Black pomfret with rich flavor — ideal for grilling and curries.", description: "Black pomfret delivers a deeper flavor profile loved across South Asian and Middle Eastern kitchens. Frozen at peak freshness for consistent quality.", features: ["Whole fish, multiple grades", "High meat yield", "Restaurant & retail packs", "Cold-chain certified"], keywords: "black pomfret Dubai, frozen fish UAE, pomfret supplier" },
    { slug: "nile-perch-fillet", name: "Nile Perch Fillet", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Nileperch_Fillet.png", short: "Boneless Nile perch fillets — versatile, mild and cost-effective.", description: "Nile perch fillets are a staple for fish & chips, grilling and buffet service. Skinless, boneless fillets with uniform portion sizes for easy kitchen prep.", features: ["Skinless boneless fillets", "IQF individual portions", "Mild flavor profile", "Excellent for foodservice"], keywords: "Nile perch fillet Dubai, frozen fish fillet UAE, perch supplier Dubai" },
    { slug: "hamour-fillet", name: "Hamour Fillet", category: "seafood", image: "assets/ProductImages/Seafood/Hamour_Fillet.png", short: "Hamour (grouper) fillets — the premium Gulf fish for upscale menus.", description: "Hamour is the crown jewel of Gulf seafood. We supply frozen hamour fillets and portions for five-star hotels, fine dining and premium retail seafood sections.", features: ["Premium Gulf grouper", "Fillet & portion cuts", "Five-star hotel grade", "Limited seasonal availability"], keywords: "hamour fillet Dubai, grouper fillet UAE, hamour supplier Dubai" },
    { slug: "salmon-fillet", name: "Salmon Fillet", category: "seafood", image: "assets/ProductImages/Seafood/Salmon_Fillet.png", short: "Premium salmon fillets for fine dining, retail and health-focused menus.", description: "Atlantic and Pacific salmon fillets — rich in flavour and ideal for grilling, smoking, sushi-grade applications and premium retail counters. Skin-on and skinless options with consistent portion weights.", features: ["Skin-on & skinless fillets", "Premium restaurant grade", "IQF portion control", "Popular in hotels & retail"], keywords: "salmon fillet Dubai, frozen salmon UAE, salmon supplier Dubai" },
    { slug: "squid-whole", name: "Squid (Whole)", category: "seafood", image: "assets/ProductImages/Seafood/Squid_Whole.png", short: "Whole frozen squid for calamari, grilling and Asian cuisine.", description: "Cleaned and whole frozen squid from trusted fisheries. Ideal for calamari rings, stuffed squid, stir-fries and charcoal grilling across diverse menu styles.", features: ["Whole & cleaned options", "Multiple size categories", "Low moisture, high yield", "Popular in Asian & Mediterranean menus"], keywords: "frozen squid Dubai, whole squid UAE, calamari supplier Dubai" },
    { slug: "squid-trimmed", name: "Squid (Trimmed)", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Squid_Trimmed.png", short: "Ready-to-cook trimmed squid — tubes, rings and tentacles.", description: "Pre-trimmed squid products save kitchen labor and reduce waste. Available as tubes, rings, tentacles and scored fillets for quick service restaurants and catering.", features: ["Tubes, rings & tentacles", "Labor-saving prep", "IQF for portion control", "Consistent sizing"], keywords: "trimmed squid Dubai, squid rings UAE, calamari rings supplier" },
    { slug: "seafood-mix", name: "Seafood Mix", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Seafood_Mix.png", short: "Curated frozen seafood mix for paella, pasta and buffet service.", description: "A balanced blend of shrimp, squid, mussels and fish pieces — perfect for paella, seafood pasta, chowders and mixed grill platters.", features: ["Balanced protein blend", "IQF mixed packs", "Buffet & catering ready", "Custom blend options"], keywords: "seafood mix Dubai, frozen seafood blend UAE, paella mix supplier" },
    { slug: "pangasius-fillet", name: "Pangasius Fillet (Basa/Douri)", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Pangasius_Basa_Douri.png", short: "Pangasius (basa/douri) fillets — affordable, mild and versatile.", description: "Pangasius fillets are among the most popular white fish in foodservice. Boneless, skinless fillets ideal for frying, baking, curries and fish burgers.", features: ["Basa & douri varieties", "Boneless skinless fillets", "Cost-effective white fish", "High-volume supply"], keywords: "pangasius fillet Dubai, basa fish UAE, douri fillet supplier Dubai" },
    { slug: "scallops", name: "Scallops", category: "seafood", image: "assets/ProductImages/Seafood/Frozen_Scallops.png", short: "Premium frozen scallops for fine dining and upscale retail.", description: "Dry-packed scallops with natural sweetness and firm texture. Available in U10, 10/20 and 20/30 counts for searing, grilling and sushi applications.", features: ["Dry-packed, no added water", "Multiple count sizes", "Fine dining grade", "IQF for easy portioning"], keywords: "frozen scallops Dubai, scallop supplier UAE, premium seafood Dubai" },

    { slug: "frozen-chicken-whole", name: "Frozen Chicken Whole", category: "poultry", image: "assets/ProductImages/Poultry/Frozen_Chicken_Whole.png", short: "Whole frozen chicken for roasting, grilling and bulk foodservice.", description: "Grade-A whole frozen chickens from approved processing plants. Available in multiple weight ranges for supermarkets, rotisserie counters and catering operations.", features: ["Grade-A quality", "Multiple weight ranges", "Halal certified", "Bulk & retail packs"], keywords: "frozen whole chicken Dubai, chicken supplier UAE, halal chicken Dubai" },
    { slug: "frozen-chicken-breast", name: "Frozen Chicken Breast", category: "poultry", image: "assets/ProductImages/Poultry/Frozen_Chicken_Breast.png", short: "Boneless skinless chicken breast — the foodservice workhorse.", description: "Premium frozen chicken breast fillets with consistent sizing. Ideal for grilling, shredding, marinating and portion-controlled menu items across HORECA.", features: ["Boneless skinless fillets", "IQF individual portions", "Trim A grade", "High-volume supply"], keywords: "frozen chicken breast Dubai, chicken breast supplier UAE" },
    { slug: "frozen-chicken-leg-quarter", name: "Frozen Chicken Leg Quarter", category: "poultry", image: "assets/ProductImages/Poultry/Frozen_Chicken_Leg_quarter.png", short: "Leg quarters for grilling, frying and value-menu offerings.", description: "Frozen chicken leg quarters (drumstick + thigh) — a menu favorite for grills, fried chicken concepts and cafeteria service.", features: ["Drumstick + thigh combo", "Multiple weight grades", "Grill & fry ready", "Competitive pricing"], keywords: "chicken leg quarter Dubai, frozen chicken legs UAE" },

    { slug: "indian-mutton-carcass", name: "Indian Mutton (Carcass)", category: "meat", image: "assets/ProductImages/Meat/Indian_Mutton_Carcass.png", short: "Fresh and frozen Indian mutton carcass for butchery and foodservice.", description: "Premium Indian mutton carcass sourced from approved abattoirs. Available fresh and frozen for butcheries, hotels and traditional Arabic & South Asian cuisine.", features: ["Fresh & frozen options", "Halal certified", "Full carcass & half carcass", "Consistent fat coverage"], keywords: "Indian mutton Dubai, mutton carcass UAE, halal mutton supplier Dubai" },
    { slug: "frozen-indian-beef-cuts", name: "Frozen Indian Beef Cuts", category: "meat", image: "assets/ProductImages/Meat/Indian_Beef_Cuts.png", short: "Frozen Indian beef cuts for retail butcheries and restaurants.", description: "A full range of frozen Indian beef cuts including cubes, mince, stew pieces and premium steaks. Processed under strict hygiene standards with reliable cold-chain delivery.", features: ["Cubes, mince & stew cuts", "Premium steak options", "Quality-controlled processing", "Custom cutting available"], keywords: "frozen beef Dubai, Indian beef cuts UAE, beef supplier Dubai" },

    { slug: "fresh-eggs", name: "Fresh Eggs", category: "eggs", image: "assets/ProductImages/Eggs/Fresh_Eggs.png", short: "Farm-fresh eggs for bakeries, hotels and commercial kitchens.", description: "High-quality fresh eggs supplied in trays and bulk packs for bakeries, hotels, cloud kitchens and supermarket chains across the UAE.", features: ["Grade A large & medium", "Tray & bulk packs", "Consistent shell quality", "Reliable weekly supply"], keywords: "fresh eggs Dubai, egg supplier UAE, commercial eggs Dubai" },

    { slug: "dates", name: "Dates", category: "other", image: "assets/ProductImages/Other/Dates.png", short: "Premium dates — Medjool, Ajwa, Deglet Noor and more.", description: "A curated selection of premium dates from the Middle East and North Africa. Perfect for retail gifting, hospitality welcome trays and Ramadan promotions.", features: ["Medjool, Ajwa & Deglet Noor", "Retail & bulk packs", "Gift packaging options", "Year-round availability"], keywords: "dates supplier Dubai, Medjool dates UAE, wholesale dates Dubai" },
    { slug: "ghee", name: "Ghee", category: "other", image: "assets/ProductImages/Other/Ghee.png", short: "Pure ghee for traditional cooking, bakeries and food manufacturing.", description: "Premium clarified butter (ghee) in tins and bulk packs for restaurants, sweet shops and food manufacturers requiring authentic flavor.", features: ["Pure cow ghee", "Tin & bulk packs", "Long shelf life", "Export quality"], keywords: "ghee supplier Dubai, pure ghee UAE, clarified butter Dubai" },
    { slug: "vegetables", name: "Vegetables", category: "other", image: "assets/ProductImages/Other/Vegetables.png", short: "Fresh and frozen vegetables for kitchens and food processors.", description: "A wide range of fresh and IQF frozen vegetables including peas, corn, mixed vegetables, spinach and more for commercial kitchens.", features: ["Fresh & IQF frozen", "Mixed veg & single items", "Food processor packs", "Seasonal fresh produce"], keywords: "vegetables supplier Dubai, frozen vegetables UAE, IQF vegetables Dubai" },
    { slug: "grains-cereals", name: "Grains & Cereals", category: "other", image: "assets/ProductImages/Other/Grain&Cereals.png", short: "Rice, wheat, oats and cereals for commercial buyers.", description: "Staple grains and cereals including basmati rice, long grain rice, wheat flour, oats and specialty grains for restaurants, caterers and retailers.", features: ["Basmati & long grain rice", "Wheat flour & semolina", "Bulk sack & bag packs", "Multiple origin options"], keywords: "rice supplier Dubai, grains UAE, basmati rice Dubai, cereals wholesale" },
    { slug: "fruits", name: "Fruits", category: "other", image: "assets/ProductImages/Other/Fruits.png", short: "Seasonal and imported fruits for retail and hospitality.", description: "Imported and seasonal fruits sourced for supermarkets, hotels and catering. From tropical fruits to berries and citrus — quality inspected on arrival.", features: ["Imported & seasonal", "Retail & foodservice packs", "Quality inspected", "Cold storage handled"], keywords: "fruit supplier Dubai, imported fruits UAE, wholesale fruits Dubai" },
    { slug: "cheese", name: "Cheese", category: "other", image: "assets/ProductImages/Other/Cheese.png", short: "International cheese varieties for retail and foodservice.", description: "A selection of imported cheeses including mozzarella, cheddar, feta, cream cheese and specialty varieties for pizzerias, delis and hotels.", features: ["Mozzarella, cheddar & feta", "Block, shredded & sliced", "Pizzeria & deli packs", "Imported brands"], keywords: "cheese supplier Dubai, mozzarella UAE, wholesale cheese Dubai" },
    { slug: "dairy-products", name: "Dairy Products", category: "other", image: "assets/ProductImages/Other/DiaryProducts.png", short: "Milk, butter, cream and yogurt for commercial operations.", description: "Complete dairy range including fresh milk, UHT milk, butter, cream, yogurt and laban for supermarkets, cafes and institutional buyers.", features: ["Milk, butter & cream", "Fresh & UHT options", "Institutional packs", "Multiple brands"], keywords: "dairy supplier Dubai, milk wholesale UAE, dairy products Dubai" }
  ],

  blog: [
    { slug: "dubai-gcc-food-trading-hub", title: "Why Dubai is the GCC's Premier Food Trading Hub", date: "2026-03-15", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=80", excerpt: "Dubai's strategic location, world-class logistics and free-zone infrastructure make it the beating heart of food trade in the Middle East.", readTime: "6 min", listed: true, keywords: "Dubai food trading, GCC food hub, Dubai food import export", content: `<p>Dubai has transformed from a regional trading post into the undisputed food distribution capital of the GCC. With Jebel Ali Port handling millions of TEUs annually and Dubai International Airport connecting to over 240 destinations, the emirate offers unmatched access to global food supply chains.</p><p>For food trading companies like Hungerfill Foods, Dubai's free-zone ecosystem — including JAFZA and Dubai Multi Commodities Centre — provides streamlined customs clearance, re-export facilities and tax advantages that reduce time-to-market for frozen seafood, poultry, meat and specialty products.</p><h3>Key advantages for food buyers</h3><ul><li>48-hour delivery reach to all GCC countries</li><li>Temperature-controlled warehousing at scale</li><li>Multi-origin sourcing under one roof</li><li>Halal certification infrastructure</li></ul><p>Whether you operate a five-star hotel in Abu Dhabi or a supermarket chain in Oman, sourcing through a Dubai-based trader like Hungerfill Foods means faster lead times, consolidated shipments and a single point of accountability for quality.</p>` },
    { slug: "sourcing-frozen-seafood-uae", title: "A Buyer's Guide to Sourcing Premium Frozen Seafood in the UAE", date: "2026-03-08", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80", excerpt: "What to look for when selecting a frozen seafood supplier — from IQF standards to cold-chain compliance.", readTime: "7 min", listed: true, keywords: "frozen seafood UAE, seafood supplier Dubai, IQF seafood", content: `<p>The UAE seafood market exceeds AED 2 billion annually, driven by a diverse population with appetites spanning Arabic grills, Asian stir-fries and European fine dining. Frozen seafood plays a critical role in meeting this demand year-round.</p><h3>What defines premium frozen seafood?</h3><ul><li><strong>Blast freezing at source:</strong> Fish frozen within hours of catch retain texture and flavor far better than slow-frozen alternatives.</li><li><strong>IQF technology:</strong> Individual Quick Freezing prevents clumping and allows precise portion control.</li><li><strong>Glazing standards:</strong> Reputable suppliers maintain glazing below 10% — excess ice means you're paying for water.</li><li><strong>Cold-chain integrity:</strong> From container to warehouse to delivery truck, temperatures must stay below -18°C.</li></ul><p>At Hungerfill Foods, every seafood shipment is received, inspected and stored in temperature-controlled cold storage before dispatch to hotels, restaurants and retailers across Dubai and the wider UAE.</p>` },
    { slug: "haccp-cold-chain-guide", title: "Cold Chain Logistics: What Every Food Buyer Should Know", date: "2026-02-28", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=900&q=80", excerpt: "Understanding cold-chain logistics is essential for any commercial food buyer in the UAE.", readTime: "5 min", listed: true, keywords: "cold chain UAE, food logistics Dubai, frozen food storage UAE", content: `<p>Food quality depends on more than sourcing — it depends on how products are stored and transported. For commercial buyers in the UAE, understanding cold-chain management is essential.</p><h3>Cold-chain essentials</h3><ul><li>Receiving temperature logs for every shipment</li><li>Calibrated storage freezers with alarm systems</li><li>Insulated delivery vehicles with temperature monitoring</li><li>First-expiry-first-out (FEFO) inventory rotation</li></ul><p>When evaluating suppliers, ask for temperature monitoring records and product traceability documentation. Hungerfill Foods maintains full traceability from origin to delivery.</p>` },
    { slug: "indian-mutton-uae-restaurants", title: "Indian Mutton vs Local Lamb: A Guide for UAE Restaurants", date: "2026-02-18", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=900&q=80", excerpt: "Understanding the differences between Indian mutton and local lamb helps chefs create authentic dishes with the right protein.", readTime: "6 min", listed: true, keywords: "Indian mutton Dubai, mutton supplier UAE, lamb vs mutton", content: `<p>In UAE kitchens, the terms "mutton" and "lamb" are often used interchangeably, but they refer to distinctly different products with unique culinary applications.</p><h3>Indian mutton (goat)</h3><p>Indian mutton typically refers to goat meat, prized for its lean profile and distinctive flavor. It's the protein of choice for biryanis, karahi, haneeth and traditional Yemeni and South Asian dishes. The meat has less fat than lamb, requiring slower cooking to achieve tenderness.</p><h3>Local and imported lamb</h3><p>Lamb (sheep meat) tends to be richer and fattier, ideal for grills, roasts and Arabic machboos. Australian and New Zealand lamb dominates the premium segment, while Indian and Pakistani lamb offers cost-effective alternatives.</p><p>Hungerfill Foods supplies both fresh and frozen Indian mutton carcass with halal certification, serving butcheries, hotels and restaurants that demand authentic flavor profiles.</p>` },
    // Temporarily hidden from blog listing
    // { slug: "poultry-cuts-hotel-catering", title: "Top Poultry Cuts for Hotel & Catering Operations", ...
    { slug: "poultry-cuts-hotel-catering", title: "Top Poultry Cuts for Hotel & Catering Operations", date: "2026-02-10", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1604503468506-440dae35f54d?w=900&q=80", excerpt: "From breast fillets to leg quarters — choosing the right chicken cut can reduce food cost and kitchen labor.", readTime: "5 min", listed: false, keywords: "poultry supplier Dubai, chicken cuts UAE, hotel catering Dubai", content: `<p>Chicken is the most consumed protein in the UAE foodservice sector. For hotel and catering buyers, selecting the right cut impacts food cost, prep time and menu versatility.</p><h3>High-demand cuts</h3><ul><li><strong>Breast fillets:</strong> The all-rounder for grills, salads, sandwiches and shredded applications. IQF portions eliminate thawing waste.</li><li><strong>Leg quarters:</strong> Best value for BBQ buffets, fried chicken and cafeteria service.</li><li><strong>Whole chicken:</strong> Ideal for rotisserie, stuffed roasts and traditional roastery counters.</li></ul><p>Hungerfill Foods offers all major frozen chicken cuts in bulk packs with halal certification and consistent sizing for portion-controlled kitchens.</p>` },
    { slug: "sustainable-seafood-middle-east", title: "Sustainable Seafood Sourcing Trends in the Middle East", date: "2026-01-25", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=900&q=80", excerpt: "How hotels and restaurants in the GCC are embracing responsible seafood sourcing without compromising menu quality.", readTime: "6 min", listed: true, keywords: "sustainable seafood UAE, responsible fishing Dubai, seafood trends GCC", content: `<p>Sustainability is moving from buzzword to business requirement across the GCC hospitality sector. Five-star hotels and restaurant groups are increasingly demanding traceable, responsibly sourced seafood.</p><h3>Key trends</h3><ul><li><strong>Aquaculture growth:</strong> Farmed shrimp, pangasius and tilapia reduce pressure on wild stocks while ensuring year-round supply.</li><li><strong>MSC & ASC certifications:</strong> Marine Stewardship Council and Aquaculture Stewardship Council labels are appearing on menus and procurement specs.</li><li><strong>Local species promotion:</strong> Hamour, sherri and other Gulf species are being highlighted as regional delicacies.</li><li><strong>Waste reduction:</strong> Trimmed and portioned products reduce kitchen waste and improve yield.</li></ul><p>Hungerfill Foods works with certified fisheries and farms to offer sustainable options alongside traditional products, helping clients meet their sustainability goals.</p>` },
    // Temporarily hidden from blog listing
    // { slug: "choosing-b2b-food-supplier-dubai", title: "How to Choose the Right B2B Food Supplier in Dubai", ...
    { slug: "choosing-b2b-food-supplier-dubai", title: "How to Choose the Right B2B Food Supplier in Dubai", date: "2026-01-12", author: "Hungerfill Team", image: "https://images.unsplash.com/photo-1556740758-90de374c12ef?w=900&q=80", excerpt: "Seven criteria every restaurant, hotel and retailer should evaluate before signing with a food trading partner.", readTime: "7 min", listed: false, keywords: "B2B food supplier Dubai, food distributor UAE, wholesale food Dubai", content: `<p>Choosing a B2B food supplier is one of the most consequential decisions a food business makes. The right partner ensures consistent quality, competitive pricing and reliable delivery. The wrong one leads to stockouts, quality complaints and wasted margin.</p><h3>Seven evaluation criteria</h3><ol><li><strong>Product range:</strong> Can they supply your full basket — seafood, poultry, meat, eggs and dry goods?</li><li><strong>Cold-chain capability:</strong> Do they own or control temperature-controlled storage and delivery?</li><li><strong>Certifications:</strong> Halal and municipality approvals should be current and verifiable.</li><li><strong>Delivery reliability:</strong> Ask for references and check delivery track records.</li><li><strong>Pricing transparency:</strong> Clear invoicing without hidden fees or inconsistent weights.</li><li><strong>Responsiveness:</strong> Can you reach a sales manager quickly when you need an urgent order?</li><li><strong>Flexibility:</strong> Will they accommodate custom cuts, pack sizes and mixed-container orders?</li></ol><p>Hungerfill Foods checks every box. Contact our sales team at sales@hungerfill.com or call 050 5056049 to discuss your requirements.</p>` }
  ]
};

if (typeof module !== "undefined") module.exports = HUNGERFILL_DATA;
